### ISSUE TITLE
gtk/gtk.h no such file or directory

### ISSUE THREAD

**Issue by Jip-Hop** [deiv/driftnet#14]
I'm trying to compile Driftnet on Kali Linux (Raspberry Pi).
However I get the following error when running make:
`gtk/gtk.h no such file or directory`
I've made sure all the dependencies `./configure` checks for are installed, but still make fails.
Any idea why?

**Comment by deiv** [comment]
Looks like pkg-config is not pulling the required include paths for gtk:

`-I/usr/include/gtk-2.0 -I/usr/include/atk-1.0 `

 maybe fixed by e5abae731f7781c8bc15666920d8fde02722c076, could you take a look ?

**Comment by 8zf** [comment]
I met this problem, too. After checking all issues here, seems that this is not solved yet. Could anyone help :)

**Comment by deiv** [comment]
Gtk libraries or pkg-confif related issues.

As the other similar bugs are fixed and close, theres no reason to maintain this bug open.

Seems not related to Driftnet itselfs.
